spring:
  application:
    name: catalog-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog_db

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
