spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog_test_db  # <--- base de datos distinta
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    enabled: false
