spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog1_db
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      movieServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s


