spring:
  application:
    name: catalog-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog_db

  config:
    import: optional:configserver:http://config-server:8888

  jpa:
    hibernate:
      ddl-auto: create-drop

  redis:
    host: localhost
    port: 6379
    password: ""  # si no tenés contraseña

  cache:
    type: redis   # indica que usaremos Redis como backend del cache

server:
  port: 8081

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

