server:
  port: 9090

spring:
  application:
    name: api-gateway

  spring:
    config:
      import: optional:configserver:http://config-server:8888


    cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/rating/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/recommendation/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
