spring:
  application:
    name: rating-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/rating_db

  redis:
    host: localhost
    port: 6379
    password: ""  # si no tenés contraseña

  cache:
    type: redis   # indica que usaremos Redis como backend del cache

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web: DEBUG
