spring:
  application:
    name: rating-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/rating_db

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web: DEBUG
