spring:
  application:
    name: recommendation-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/recommendation_db

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      recommendationServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        recordExceptions:
          - feign.FeignException
          - java.net.ConnectException
          - java.lang.Exception


feign:
  client:
    config:
      default:
        retryer:
          period: 0
          maxPeriod: 0
          maxAttempts: 1
