spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/user_db

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
  instances:
    ratingService:
      registerHealthIndicator: true
      record-exceptions:
        - feign.RetryableException
      wait-duration-in-open-state: 5s
      failure-rate-threshold: 50
      ring-buffer-size-in-closed-state: 5

