apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: mini-netflix
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server-container
        image: veradelacruz/config-server:latest
        ports:
        - containerPort: 8888
