apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: mini-netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: veradelacruz/recommendation-service:latest
          ports:
            - containerPort: 8083
