server:
  port: 8762

spring:
  application:
    name: eureka-server
  config:
    import: "optional:config-server:http://config-server:8888"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"   # permite que /actuator/health esté accesible
  endpoint:
    health:
      show-details: ALWAYS
