apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: mini-netflix
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
