apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: mini-netflix
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30061
  selector:
    app: eureka
