apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: mini-netflix
spec:
  selector:
    app: rating-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
