apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: mini-netflix
spec:
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
