apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mini-netflix
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
